---
name: CI Workflow

on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x', '24.x']
        os: ['ubuntu-24.04', 'ubuntu-22.04', 'windows-2022']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run ci-workflow
      - name: Upload test report to codecov.io
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage report to codecov.io
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: 'coverage.lcov'
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
