---
name: Test

on: [push, pull_request]

jobs:
  install-dependencies-and-run-tests:
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
      - name: Running tests
        run: npm test
      - name: Gather coverage report
        run: npx nyc report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: './coverage.lcov'
          report_type: 'coverage'
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
