---
name: Test

on: [push, pull_request]

jobs:
  install-dependencies-and-run-tests:
    runs-on: ['ubuntu-latest', 'windows-latest']
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
      - name: Running tests
        run: npm test
