---
name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x', '24.x']
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Gather coverage report
        run: npx nyc report --reporter=text-lcov > coverage.lcov
      - name: Upload report to codecov.io
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          files: './coverage.lcov'
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
